server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/productsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: "productservice"
  config:
    import: optional:configserver:http://localhost:8071
info:
  app:
    name: "productservice"
    description: "Product Service"
    version: "1.0"

endpoints:
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true