version: "1.0"
services:
  configserver:
    image: devjangir/configserver:s2
    container_name: configserver
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
    ports:
      - "8071:8071"
    networks:
      - devkart
  productsdb:
    image: mysql:8.0
    #restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: productsdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - devkart
  usersdb:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ROOT_PASSWORD: root
    #restart: always
    ports:
      - "3307:3306"
    networks:
      - devkart
  productservice:
    image: devjangir/productservice:s3
    ports:
      - "8080:8080"
    networks:
      - devkart
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://productsdb:3306/productsdb
    depends_on:
      productsdb:
        condition: service_healthy
  userservice:
    image: devjangir/userservice:s2
    ports:
      - "8081:8081"
    networks:
      - devkart
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://usersdb:3306/usersdb
    depends_on:
      usersdb:
        condition: service_healthy
  # Database images

networks:
  devkart:
    driver: bridge
