server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/usersdb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
  application:
    name: "userservice"

info:
  app:
    name: "productservice"
    description: "Product Service"
    version: "1.0"

endpoints:
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true